-스레드풀과 커스텀 이벤트

-예외처리하기
promise - catch로 에러처리
async await에서 try-catch를 통한 에러처리
예외: 처리하지 못한 에러를 뜻함
에러가 발생시 처리 못하는 경우 -> 노드 스레드를 멈춘다.
fs같은 경우에는 try-catch로 할 필요 없음
프로미스에서는 catch안붙여도 실행은 가능 (경고는 나옴) 하지만 catch를 붙이는게 좋음 (노드 버전올라가면 에러 확률 높아짐)
